name: LuckyWars
version: 1.5.1
load: STARTUP
main: LuckyWars\LuckyWars
api: 3.15.0
description: LuckyWars Minigame for your PocketMine-MP server
website: https://github.com/BlockNetworks/LuckyWars

commands:
  lw:
    usage: /lw <leave-make>
    description: LuckyWars
  lwstart:
    usage: /lwstart
    description: Starts LuckyWars game
