name: LuckyWars
version: 1.5.1
load:
main: LuckyWars\LuckyWars
api: 1.0.0, 2.0.0, 3.0.0, 4.0.0, 5.0.0
description: An advanced plugin for LuckyWars

commands:
  lw:
    usage: /lw <leave-make>
    description: LuckyWars
  lwstart:
    usage: /lwstart
    description: Starts LuckyWars game
