name: LuckyWars
version: 1.5.1
load: STARTUP
main: LuckyWars\LuckyWars
api: 3.0.0, 4.0.0
description: LuckyWars Minigame for your PocketMine-MP server

commands:
  lw:
    usage: /lw <leave-make>
    description: LuckyWars
  lwstart:
    usage: /lwstart
    description: Starts LuckyWars game
